import jsPDF from 'jspdf';

/**
 * Escape a value for CSV
 * @param {any} val
 * @returns {string}
 */
const escape = (val) => `"${String(val ?? '').replace(/"/g, '""')}"`;

/**
 * Generate CSV string from rows array
 * @param {object[]} rows
 * @param {string[]} headers - column keys matching row properties
 * @returns {string}
 */
export const generateCSV = (rows, headers = ['Indicator', 'Category', 'Ranking', 'Score', 'Year', 'Source']) => {
  const headerRow = headers.map(escape).join(',');
  const dataRows = rows.map(row => headers.map(h => escape(row[h])).join(','));
  return [headerRow, ...dataRows].join('\n');
};

/**
 * Trigger browser download of a CSV string
 * @param {string} content
 * @param {string} filename
 */
export const downloadCSV = (content, filename = 'indialens-export.csv') => {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Export indicator data as a PDF
 * @param {string} title - Indicator name
 * @param {object} data - { rank, score, description, recommendations }
 */
export const exportPDF = (title, data = {}) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header background
  doc.setFillColor(26, 35, 126);
  doc.rect(0, 0, pageWidth, 30, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('IndiaLens – AI Global Progress Dashboard', 15, 12);
  doc.setFontSize(12);
  doc.text(title, 15, 22);

  // Reset text
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  let y = 40;

  // Stats
  if (data.rank) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Global Rank: #${data.rank}`, 15, y);
    y += 8;
    doc.text(`Score: ${data.score ?? 'N/A'}`, 15, y);
    y += 8;
    if (data.totalCountries) {
      doc.setFont('helvetica', 'normal');
      doc.text(`Out of ${data.totalCountries} countries`, 15, y);
      y += 10;
    }
  }

  // Description
  if (data.description) {
    doc.setFont('helvetica', 'bold');
    doc.text('About this Indicator:', 15, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(data.description, pageWidth - 30);
    doc.text(lines, 15, y);
    y += lines.length * 5 + 8;
  }

  // Recommendations
  if (data.recommendations?.length) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('AI Recommendations:', 15, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    data.recommendations.forEach((rec, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, pageWidth - 30);
      doc.text(lines, 15, y);
      y += lines.length * 5 + 3;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by IndiaLens on ${new Date().toLocaleDateString()} | Data Year: 2026`, 15, 287);

  doc.save(`${title.replace(/\s+/g, '_')}_IndiaLens.pdf`);
};
